### Basic Application Settings

### Server Settings
server:
  port: 8888
### Actuator Settings
management:

  endpoints:
    enabled-by-default: true
    health:
      show-details: "always"
    logfile:
      external-file: "tenant.log"
    web:
      exposure:
        include: "*"

### Data Source Settings
spring:
  h2:
    console:
      enabled: true
      path: "/h2"
  #jpa sql logs
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  liquibase:
    enabled: true

### Log Settings
logging:
  config: "log4j2-spring.xml"

### Tenant datasource Settings
tenants:
  datasources:
    default:
      driver-class-name: "org.h2.Driver"
      username: "sa"
      password:
      url: "jdbc:h2:mem:defaulttestdb"
      maximum-pool-size: 16
      pool-name: Hikari-Default
    example:
      driver-class-name: "org.h2.Driver"
      username: "sa"
      password:
      url: "jdbc:h2:mem:exampletestdb"
      maximum-pool-size: 16
      pool-name: Hikari-Example